### ISSUE TITLE
Support for Non-DHCP mode

### ISSUE THREAD

**Issue by sorvis** [ArieLevs/Raspberry-WiFi-Repeater#13]
Hello,

If we using routing traffic between the extended network and the existing network to utilize the existing DHCP server on the existing network instead of having another one for this network?

**Comment by ArieLevs** [comment]
Hi @sorvis 

Currently this repo does not support raspberry configuration as an extended network (only as routed with new network).
I'll try to add this feature during this week.

**Comment by ArieLevs** [comment]
@sorvis please check PR #17 

you can now use raspberry pi using the existing DHCP from your router, extending you local network.

The PR was tested bridging `eth0` with `wlan0` only.
still not tested for `wlan1` and `wlan0` but this should be pretty straight forward.
