### ISSUE TITLE
Slow WiFi speed

### ISSUE THREAD

**Issue by Airmonkdev** [ArieLevs/Raspberry-WiFi-Repeater#18]
**Describe the bug**
Slow WiFi connection speed with extended configuration (3):
I can reach about 70/80Mbps with speedtest-cli on my raspberry but if I perform the same test from a device connected to the extended WiFi AC I can reach only 1/2Mbps. I've added "wmm_enabled=1" and "ieee80211d=1" to the hostapd.conf and Ican now reach about 8/10Mbps but I've got a Raspberry Pi 3B+ so I was expected to reach about 40/50Mbps at least

**To Reproduce**
1. Connect a device to the extendef WiFi AP
2. Comare eth speed vs WiFi speed

**Expected behavior**
About 40/50Mbps in this scenario

**System information:**
 - OS version: Raspbian GNU/Linux 11 (bullseye)
 - Kernel version: 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux

**Comment by ArieLevs** [comment]
Hi @Airmonkdev ,
you are correct, when I test directly via **LAN** connection, I get almost 900 Mbps
```
   Speedtest by Ookla

      Server: XXXXX XXXXX (id: XXXX)
         ISP: XXXXX XXXXX
Idle Latency:     1.60 ms   (jitter: 0.04ms, low: 1.55ms, high: 1.64ms)
    Download:   896.70 Mbps (data used: 439.4 MB)
                  2.37 ms   (jitter: 5.59ms, low: 1.48ms, high: 207.96ms)
      Upload:   107.64 Mbps (data used: 152.7 MB)
                  1.72 ms   (jitter: 11.02ms, low: 1.44ms, high: 414.44ms)
 Packet Loss:     0.0%w

```
when testing using a mobile device connected via **wifi** directly to my router I get 310 Mbps, then when using raspberry as extended network speed drops to **43 Mbps**, with WMM turned on

historically I've creating these docs as my use case was for raspberry to serve very basic IOT devices, that were not even able to connect to the AP if wmm was enabled, I assume that enabling it by default so users could get ieee80211ac/ieee80211n support
there might be other factors that impact down/up speeds performance, as wifi channel, encryption, etc, I know that [PR#20](https://github.com/ArieLevs/Raspberry-WiFi-Repeater/pull/20) does not explicitly fixes this, but I'm working on docs upgrade for Debian bookworm version support and I hope we could see improvement.

tested using RPi5 Linux 6.6.31+rpt-rpi-2712 (Debian GNU/Linux 12 bookworm)
