### ISSUE TITLE
ansible fails on "Update iptables" step

### ISSUE THREAD

**Issue by IIerpos** [ArieLevs/Raspberry-WiFi-Repeater#2]
The relevant error:

TASK [setup_raspberry_access_point : Access Point | Update iptables] **************************************************************************************************************
fatal: [192.168.0.10]: FAILED! => {"changed": true, "cmd": "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE", "delta": "0:00:00.047784", "end": "2021-02-20 22:03:51.406696", "msg": "non-zero return code", "rc": 1, "start": "2021-02-20 22:03:51.358912", "stderr": "iptables/1.8.2 Failed to initialize nft: Protocol not supported", "stderr_lines": ["iptables/1.8.2 Failed to initialize nft: Protocol not supported"], "stdout": "", "stdout_lines": []}

I am running raspios-buster lite

**Comment by ArieLevs** [comment]
@IIerpos can you please post the output for this commands: `iptables -V` and `uname -a`
