### ISSUE TITLE
wlan1: interface does not exist

### ISSUE THREAD

**Issue by africantearoa** [ArieLevs/Raspberry-WiFi-Repeater#3]
Hi there,

I have been trying to manually set up a wireless repeater.
I managed to get through your instructions until the very last line, where the code "sudo brctl addif br0 wlan1" gives the result "wlan1 interface does not exist".
I've gone through the instructions twice, both times with the same issue

Please let me know what I might be doing wrong. 
Thanks

**Comment by africantearoa** [comment]
Have realised I had not correctly installed the wifi dongle, so there was no wlan1. 
However now I have this set up, but get an error with the bridging:

sudo brctl addif br0 wlan1
"can't add wlan1 to bridge br0: Operation not supported"

**Comment by gpavelski** [comment]
Hi @africantearoa ,

In the recent days I was running on the same issues as yours, spending days reading tutorials and forums about how to configure Pi as a wireless hotspot, there was always some problem to solve.
When I was about to give up, I found this repository: [create_ap](https://github.com/oblique/create_ap), and that worked really great.

Try to clone it and install on your Raspberry. First stop the running services:

sudo systemctl stop hostapd.service
sudo systemctl stop dnsmasq.service

Finally, run the command:

create_ap wlan1 wlan0 MyAccessPoint MyPassPhrase

If it gives an error about the AP, Master, try to invert the order of wlan0 and wlan1

**Comment by ArieLevs** [comment]
Hi @africantearoa 
In order to user `wlan1` as the interface connecting to your local lan (router),
you will need to provide that interface with wifi credentials,
please try executing Ansible with these variables:
```shell
ansible-playbook -u pi --ask-pass \
    -i "<RASPBERRY_PI_IP>," \
    ansible/setup_repeater.yaml \
    -e ssid_name=<ROUTERS_SSID> \
    -e ssid_pass=<WIFI_PASSWORD>
```
change `<RASPBERRY_PI_IP>` with the ip address raspberry is reachable at,
`<ROUTERS_SSID>` name of your home wifi network,
`<WIFI_PASSWORD>` password to that network.

**Comment by ArieLevs** [comment]
Please check new documentation after merging https://github.com/ArieLevs/Raspberry-WiFi-Repeater/pull/9
